// E(<mnemonic>, "<description>")
E(INVAL, "Invalid argument")
E(NOSYS, "Not implemented")
E(IO, "IO error")
E(BUSY, "Device or resource busy")
E(NOSR, "Out of resources")
E(INVAL_SENSOR, "Invalid Distance Sensor")
E(INVAL_AIN, "Invalid Analog input")
